-- MySQL Script generated by MySQL Workbench
-- Thu Apr 14 21:54:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDiP2021x128
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2021x128
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2021x128` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2021x128` ;

-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Uloga_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Uloga_korisnika` (
  `uloga_korisnika_id` INT NOT NULL,
  `naziv_uloge` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uloga_korisnika_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Korisnik` (
  `korisnik_id` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `kor_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `uloga_korisnika_id` INT NOT NULL,
  PRIMARY KEY (`korisnik_id`, `uloga_korisnika_id`),
  INDEX `fk_Korisnik_Uloga_korisnika1_idx` (`uloga_korisnika_id` ASC) ,
  CONSTRAINT `fk_Korisnik_Uloga_korisnika1`
    FOREIGN KEY (`uloga_korisnika_id`)
    REFERENCES `WebDiP2021x128`.`Uloga_korisnika` (`uloga_korisnika_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Igra_na_srecu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Igra_na_srecu` (
  `igra_na_srecu_id` INT NOT NULL,
  `naziv_igre` VARCHAR(45) NOT NULL,
  `koliko_se_brojeva_izvlaci` INT NOT NULL,
  PRIMARY KEY (`igra_na_srecu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Fond`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Fond` (
  `fond_id` INT NOT NULL,
  `iznos_po_pogodjenom_broju` DOUBLE NOT NULL,
  `igra_na_srecu_id` INT NOT NULL,
  PRIMARY KEY (`fond_id`, `igra_na_srecu_id`),
  INDEX `fk_Fond_Igra_na_srecu1_idx` (`igra_na_srecu_id` ASC) ,
  CONSTRAINT `fk_Fond_Igra_na_srecu1`
    FOREIGN KEY (`igra_na_srecu_id`)
    REFERENCES `WebDiP2021x128`.`Igra_na_srecu` (`igra_na_srecu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Zemlja_porijekla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Zemlja_porijekla` (
  `zemlja_porijekla_id` INT NOT NULL,
  `naziv_drzave` VARCHAR(50) NOT NULL,
  `kontinent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`zemlja_porijekla_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Lutrija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Lutrija` (
  `lutrija_id` INT NOT NULL,
  `naziv_lutrije` VARCHAR(45) NOT NULL,
  `lokacija` VARCHAR(45) NOT NULL,
  `datum_osnivanja` DATE NOT NULL,
  `broj_ispostava` INT NOT NULL,
  `online_kladjenje` VARCHAR(45) NOT NULL DEFAULT 'Da',
  `zemlja_porijekla` INT NOT NULL,
  PRIMARY KEY (`lutrija_id`, `zemlja_porijekla`),
  INDEX `fk_Lutrija_Zemlja_porijekla1_idx` (`zemlja_porijekla` ASC) ,
  CONSTRAINT `fk_Lutrija_Zemlja_porijekla1`
    FOREIGN KEY (`zemlja_porijekla`)
    REFERENCES `WebDiP2021x128`.`Zemlja_porijekla` (`zemlja_porijekla_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Kolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Kolo` (
  `kolo_id` INT NOT NULL,
  `datum_isplate` DATE NOT NULL,
  `vrijeme_isplate` TIME NOT NULL,
  `status_kola` VARCHAR(45) NOT NULL DEFAULT 'Zatvoreno',
  `lutrija_id` INT NOT NULL,
  `igra_na_srecu_id` INT NOT NULL,
  PRIMARY KEY (`kolo_id`, `lutrija_id`, `igra_na_srecu_id`),
  INDEX `fk_Kolo_Lutrija1_idx` (`lutrija_id` ASC) ,
  INDEX `fk_Kolo_Igra_na_srecu1_idx` (`igra_na_srecu_id` ASC) ,
  CONSTRAINT `fk_Kolo_Lutrija1`
    FOREIGN KEY (`lutrija_id`)
    REFERENCES `WebDiP2021x128`.`Lutrija` (`lutrija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kolo_Igra_na_srecu1`
    FOREIGN KEY (`igra_na_srecu_id`)
    REFERENCES `WebDiP2021x128`.`Igra_na_srecu` (`igra_na_srecu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Lutrija_Igra_na_srecu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Lutrija_Igra_na_srecu` (
  `lutrija_id` INT NOT NULL,
  `igra_na_srecu_id` INT NOT NULL,
  `cijena_listica` INT NOT NULL,
  `vrijeme_pocetka_igre` DATETIME NOT NULL,
  `vrijeme_kraja_igre` DATETIME NOT NULL,
  PRIMARY KEY (`lutrija_id`, `igra_na_srecu_id`),
  INDEX `fk_Lutrija_has_Igra_na_srecu_Igra_na_srecu1_idx` (`igra_na_srecu_id` ASC) ,
  INDEX `fk_Lutrija_has_Igra_na_srecu_Lutrija1_idx` (`lutrija_id` ASC) ,
  CONSTRAINT `fk_Lutrija_has_Igra_na_srecu_Lutrija1`
    FOREIGN KEY (`lutrija_id`)
    REFERENCES `WebDiP2021x128`.`Lutrija` (`lutrija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lutrija_has_Igra_na_srecu_Igra_na_srecu1`
    FOREIGN KEY (`igra_na_srecu_id`)
    REFERENCES `WebDiP2021x128`.`Igra_na_srecu` (`igra_na_srecu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Listic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Listic` (
  `listic_id` VARCHAR(45) NOT NULL,
  `korisnik_id` INT NOT NULL,
  `lutrija_id` INT NOT NULL,
  `igra_na_srecu_id` INT NOT NULL,
  `uneseni_brojevi` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT '091-935',
  `email` VARCHAR(45) NOT NULL DEFAULT '@foi.hr',
  PRIMARY KEY (`listic_id`, `korisnik_id`, `lutrija_id`, `igra_na_srecu_id`),
  INDEX `fk_Korisnik_has_Igra_na_srecu_Igra_na_srecu1_idx` (`igra_na_srecu_id` ASC) ,
  INDEX `fk_Korisnik_has_Igra_na_srecu_Korisnik1_idx` (`korisnik_id` ASC) ,
  INDEX `fk_Listic_Lutrija1_idx` (`lutrija_id` ASC) ,
  CONSTRAINT `fk_Korisnik_has_Igra_na_srecu_Korisnik1`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2021x128`.`Korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik_has_Igra_na_srecu_Igra_na_srecu1`
    FOREIGN KEY (`igra_na_srecu_id`)
    REFERENCES `WebDiP2021x128`.`Igra_na_srecu` (`igra_na_srecu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Listic_Lutrija1`
    FOREIGN KEY (`lutrija_id`)
    REFERENCES `WebDiP2021x128`.`Lutrija` (`lutrija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x128`.`Lista_korisnika_prema_dobitku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x128`.`Lista_korisnika_prema_dobitku` (
  `lista_korisnika_id` INT NOT NULL,
  `listic_id` VARCHAR(45) NOT NULL,
  `korisnik_id` INT NOT NULL,
  `lutrija_id` INT NOT NULL,
  `igra_na_srecu_id` INT NOT NULL,
  `datum_igre` DATE NOT NULL,
  `iznos` DOUBLE NULL,
  PRIMARY KEY (`lista_korisnika_id`, `listic_id`, `korisnik_id`, `lutrija_id`, `igra_na_srecu_id`),
  INDEX `fk_Lista_korisnika_prema_dobitku_Listic1_idx` (`listic_id` ASC, `korisnik_id` ASC, `lutrija_id` ASC, `igra_na_srecu_id` ASC) ,
  CONSTRAINT `fk_Lista_korisnika_prema_dobitku_Listic1`
    FOREIGN KEY (`listic_id` , `korisnik_id` , `lutrija_id` , `igra_na_srecu_id`)
    REFERENCES `WebDiP2021x128`.`Listic` (`listic_id` , `korisnik_id` , `lutrija_id` , `igra_na_srecu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
